docs_dir: docs/book
site_dir: docs/html
nav:
    - index.md
    - "Progress Bars":
        - Intro: intro.md
        - Adapters: adapters.md
    - "File Upload Handlers": upload.md
site_name: laminas-progressbar
site_description: laminas-progressbar
repo_url: 'https://github.com/laminas/laminas-progressbar'
